### ISSUE TITLE
Send VINs in the correct order

### ISSUE THREAD

**Issue by jovanjellylabs** [DeFiCh/jellyfishsdk#1718]
Currently the VINs API request (https://ocean.defichain.com/v0/testnet/transactions/{transaction_id}/vins) returns VINs in incorrect order (see the image attached). It would be very useful to have those VINs in the correct order.

![IMG_3290](https://user-images.githubusercontent.com/107772201/186178132-19ab77f4-9aa3-486f-b6b5-1642f662bbfd.PNG)

**Comment by fuxingloh** [comment]
/apps whale-api
/area apps
/kind question

The 2 APIs are created by different indexers for different reasons.

https://github.com/JellyfishSDK/jellyfish/blob/ed81791462c24299029255dd62d22fae658d92e2/apps/whale-api/src/module.model/transaction.vin.ts#L51

Currently, it's sorted in lexicographic order (as above), which is required within the `whale-api` inner subsystem since we're using sorted set indexing ([LSM](https://github.com/JellyfishSDK/jellyfish/blob/ed81791462c24299029255dd62d22fae658d92e2/apps/whale-api/src/module.database/database.ts#L8-L11)). We have to follow the sorted set design for all indexed data to achieve high-performance cursor-based pagination as described below:

https://github.com/JellyfishSDK/jellyfish/blob/ed81791462c24299029255dd62d22fae658d92e2/apps/whale-api/src/module.api/_core/api.paged.response.ts#L11-L64

> There is also a strict ["rule book"](https://github.com/JellyfishSDK/jellyfish/blob/ed81791462c24299029255dd62d22fae658d92e2/apps/whale-api/src/module.database/database.spec/specifications.ts) where all indexes have to follow making one-off sorting, other than what's intentionally indexed, rather impossible.

Another point — since this is a released API and the change is considered breaking, we can't change it. I would advise you to re-sort to the data shape you need it instead of relying on the default lexi sort.

**Comment by jovanjellylabs** [comment]
And how can I sort them? Is there any api that can provide created_at for each VIN or rawTx hex?

**Comment by SantiagoDeFi** [comment]
Hey guys, we would like to follow up again since its blocking us to finish off the hardware wallet integration for Jellywallet. 

Would it be possible to extend the rpc.controller.ts and add "getrawtransaction" ? 

![telegram-cloud-document-4-5792056324015525940](https://user-images.githubusercontent.com/74860408/187251110-280fed95-4cf0-487a-8553-5c01de7f8504.jpg)

**Comment by fuxingloh** [comment]
Since this is an Open Source project, contributions are much appreciated!

The different services developed thus far are implemented and tested by various stakeholders within the ecosystem for their specific use cases. A PR (with tests) would be much appreciated if you would require something that would benefit the ecosystem. Otherwise, you can fork the project at your own will and use it however you want since this project is MIT licensed. However, for PRs created, we can't guarantee they will be merged as we have to access its impact if merged.

A few references you should take note of:

- https://github.com/JellyfishSDK/jellyfish/blob/main/CONTRIBUTING.md
- https://github.com/JellyfishSDK/.github/blob/main/CODE_OF_CONDUCT.md

**Comment by SantiagoDeFi** [comment]
Hey Fuxing,

Thanks for the answer! I really appreciate it!
We did a pull request too add „getrawtransaction“ to one of the controllers. Here the request:
https://github.com/JellyfishSDK/jellyfish/pull/1729

The PR was created by p3root, hope it fits to the guidelines. 

Cheers!
