### ISSUE TITLE
🐛 Unspendable DFIs block any transactions `(DeFiCh/wallet)`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/jellyfishsdk#1807]
#### What happened:
https://github.com/DeFiCh/wallet/issues/3663

**Comment by fuxingloh** [comment]
/area packages

It's a known issue since the `PrevoutProvider` that we use and implemented today is the bare minimum but good enough. Another implementation can be done and take into account "Immature UTXO" and filter it from the prevout provider. However, that's not enough since we still need to show that a certain amount of their UTXO is Immature.

https://github.com/JellyfishSDK/jellyfish/blob/4c35de8a08d35283abbdaf7786703ef73ce150a3/packages/jellyfish-transaction-builder/src/provider.ts#L12-L28

If we were to implement the Immature UTXO filtering, we should implement this https://github.com/JellyfishSDK/jellyfish/issues/1663 first. 

Since this is not a low-bearing fruit, I don't have an answer now; let's see.

**Comment by mrgrauel** [comment]
@fuxingloh thanks, for clarification. It's dangerous, because it blocks the user from being able to save its vaults from liquidation. I was shocked when I noted that I cannot do any transactions for 100 blocks. I was happy that I noticed the issue on a friday night, so oracles do not move much.

As soon as `setRewardAddress` is possible for a masternode owner this could become a bigger problem, because at the moment only masternode operator are able to set `rewardaddress` for all operators.

From my user glasses, it is very important to solve the problem because it could cost the user a lot of money and it's not totally his fault.

**Comment by fuxingloh** [comment]
> @fuxingloh thanks, for clarification. It's dangerous, because it blocks the user from being able to save its vaults from liquidation. I was shocked when I noted that I cannot do any transactions for 100 blocks. I was happy that I noticed it the issue on a friday night, so oracles do not move much.
> 
> As soon as `setRewardAddress` is possible for a masternode owner this could become a bigger problem, because at the moment only masternode operator are able to set `rewardaddress` for all operators.
> 
> From my user glasses, it is very important to solve the problem because it could cost the user a lot of money and kind it's not totally his fault.

/triage accepted

Great insights; let me think about this since it's not an easy fix with many legacy tech debts. Alternative for affected users please separate your `reward address` from active operational wallets.

**Comment by fuxingloh** [comment]
Not an easy change; let's approach it slowly and tackle the first issue first since that interface prevents spending. Where we can throw an error when attempting to spend immature UTXO. We can improve and expand on the basic PrevoutProvider while we're at it.

#### Issues to Tackle:

- [ ] `WhalePrevoutProvider` should ignore UTXO that are Immature (<100 confirmations)
- [ ] Whale Balance Aggregation should separately aggregate immature UTXO
- [ ] Provide additional field on whale-api to show immature category UTXO

Let me find the resources to tackle this.
